name: Deploy Cloud Function

on:
  push:
    branches:
      - 'main'
      

jobs:
  all:
    name: CI/CD workflow
    runs-on: ubuntu-latest
    environment: 
      name: wakeflow-internal 
      url: https://github.com
    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: 'Authenticate to Google Cloud'
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          
      - run: echo "${{ secrets.ENV_FILE }}" > .env
      - run: npx dotenv-to-yaml .env .env.yaml

      - run: |
            gcloud functions deploy ${{ github.event.repository.name }} \
            --env-vars-file .env.yaml \
            --region=europe-west2 \
            --runtime=nodejs18 \
            --trigger-http \
            --entry-point=api

      - run: |
            gcloud functions add-iam-policy-binding ${{ github.event.repository.name }} \
            --region=europe-west2 \
            --member="allUsers" \
            --role="roles/cloudfunctions.invoker"
